import { back1, back2, back3, back4, back5 } from "./images";

const data = [
  {
    id: "a",
    title: "Turkish champions won’t give Nwakaeme ‘high’ 3-year contract",
    imgUrl: back1,
    type: "full",
    comments: "76",
    views: "200",
    author: "Philip Maxwell",
    publicationDate: "Jan 14, 2022",
    description:
      "\t\t\tTrabzonspor chairman Ahmet Agaoglu has revealed that his club have offered Anthony Nwakaeme what they are capable of paying and waiting for the Nigerian forward to respond. He said the offer made to Nwakaeme will make him the highest paid at the club, but the team cannot afford the number of years demanded by the striker. \n\n\t\t\t“We offered Anthony Nwakaeme the highest wage we could give. The three-year contract was high for us. He is a very valuable player,” he said. The 33-year-old striker scored 13 goals in 30 league games as Trabzonspor emerged champions in Turkey.",
    comments: [
      {
        id: "1",
        body: "First comment",
        username: "Jack",
        userId: "1",
        parentId: null,
        createdAt: "2022-06-10T18:00:33.010+02:00",
      },
      {
        id: "2",
        body: "First comment first child",
        username: "Sparrow",
        userId: "2",
        parentId: "1",
        createdAt: "2022-05-10T18:00:33.010+02:00",
        replyTo: "Jack",
      },
      {
        id: "3",
        body: "Second comment",
        username: "Van Dick",
        userId: "3",
        parentId: null,
        createdAt: "2022-06-10T18:00:33.010+02:00",
      },
      {
        id: "4",
        body: "Second comment first child",
        username: "Jack",
        userId: "1",
        parentId: "3",
        createdAt: "2022-05-10T18:00:33.010+02:00",
        replyTo: "Van Dick",
      },
      {
        id: "5",
        body: "Second comment second child",
        username: "Jack",
        userId: "1",
        parentId: "3",
        createdAt: "2022-06-11T18:00:33.010+02:00",
        replyTo: "Van Dick",
      },
      {
        id: "6",
        body: "Third comment child",
        username: "Jack",
        userId: "1",
        parentId: null,
        createdAt: "2022-06-11T18:00:33.010+02:00",
      },
      {
        id: "7",
        body: "Second comment third child",
        username: "Jack",
        userId: "1",
        parentId: "3",
        createdAt: "2022-06-11T18:00:33.010+02:00",
        replyTo: "Van Dick",
      },
    ],
  },
  {
    id: "b",
    title: "War-torn Ukraine dream of World Cup morale boost",
    imgUrl: back2,
    type: "small",
    comments: "65",
    views: "600",
    author: "Philip Maxwell",
    publicationDate: "June 1, 2022",
    description:
      "\t\t\tFeatured - breaking football newsFootball News War-torn Ukraine dream of World Cup morale boost By Our Reporter On Jun 1, 2022. Ukraine’s national team are dreaming of a place at the World Cup to bring some relief to a war-torn nation as they face Scotland in a playoff semifinal on Wednesday. \n\n\t\t\tOleksandr Petrakov’s side have not played a competitive match since Russia’s invasion in February. Their trip to Scotland was postponed in March to give Ukraine the chance to fulfil the fixture.",
    comments: [
      {
        id: "1",
        body: "First comment",
        username: "Jack",
        userId: "1",
        parentId: null,
        createdAt: "2022-06-10T18:00:33.010+02:00",
      },
      {
        id: "2",
        body: "Firt comment first child",
        username: "Sparrow",
        userId: "2",
        parentId: "1",
        createdAt: "2022-05-10T18:00:33.010+02:00",
        replyTo: "Jack",
      },
      {
        id: "3",
        body: "Second comment",
        username: "Van Dick",
        userId: "3",
        parentId: null,
        createdAt: "2022-06-10T18:00:33.010+02:00",
      },
      {
        id: "4",
        body: "Second comment first child",
        username: "Jack",
        userId: "1",
        parentId: "1",
        createdAt: "2022-05-10T18:00:33.010+02:00",
        replyTo: "Jack",
      },
      {
        id: "5",
        body: "Second comment second child",
        username: "Jack",
        userId: "1",
        parentId: "3",
        createdAt: "2022-06-11T18:00:33.010+02:00",
        replyTo: "Van Dick",
      },
    ],
  },
  {
    id: "c",
    title: "Italy look to rebuild by winning ‘Finalissima’",
    imgUrl: back3,
    type: "small",
    views: "935",
    author: "Philip Maxwell",
    publicationDate: "Mar 5, 2022",
    description:
      "\t\t\tFeatured - breaking football newsFootball News Italy look to rebuild by winning ‘Finalissima’ By Our Reporter On Jun 1, 2022. Italy will look to put the disappointment of failing to qualify for the World Cup behind them and kick-start a new era for the Azzurri by beating Argentina in the ‘Finalissima’, Italy players said on Tuesday. \n\n\t\t\tThe match on Wednesday between the European champions and the Copa America winners will be played at Wembley Stadium, where Italy triumphed over England on penalties last July to win their second European Championship title.",
    comments: [],
  },
  {
    id: "d",
    title: "WCQ: Scotland try to keep eye on the prize in playoff",
    imgUrl: back4,
    type: "full",
    comments: [],
    views: "156",
    author: "Philip Maxwell",
    publicationDate: "April 16, 2022",
    description:
      "\t\t\tScotland are hoping to reach their first World Cup finals in 24 years but if Steve Clarke’s side are to make it through the playoffs it will have to be at the expense of war-torn Ukraine. The two countries face each other at Hampden Park on Wednesday and the winner will then travel to Cardiff for the final playoff game against Wales on Sunday with a place in November’s finals on the line. \n\n\t\t\tWith so much solidarity and support around the world for Ukraine, the Scots know they will have few neutrals backing them but Clarke said that his players have to block out any thoughts other than the task ahead for them in the 90 minutes on the field.",
  },
  {
    id: "e",
    title: "Ahead of playoff, Zinchenko’s dream is simply peace",
    imgUrl: back5,
    type: "small",
    comments: [],
    views: "1078",
    author: "Philip Maxwell",
    publicationDate: "May 10, 2022",
    description:
      "\t\t\tUkraine midfielder Oleksandr Zinchenko broke into tears on the eve of his team’s crucial World Cup qualifier with Scotland and said he wanted above everything to see peace in his homeland. Ukraine, which has been ravaged by war since Russia’s invasion in February, face Scotland at Hampden Park on Wednesday and if they win that game they will go on to take on Wales in Cardiff on Sunday for a place in the finals in Qatar in November. \n\n\t\t\tBut Zinchenko, who plays for Premier League champions Manchester City, said the prospect of World Cup qualification was secondary to the main hope of his countrymen.",
  },
  {
    id: "f",
    title:
      "Ahead of playoff, Zinchenko’s dream is simply peace with Mbappe at Madrid",
    imgUrl: back1,
    type: "small",
    comments: [
      {
        id: "1",
        body: "First comment",
        username: "Jack",
        userId: "1",
        parentId: null,
        createdAt: "2022-06-10T18:00:33.010+02:00",
      },
      {
        id: "2",
        body: "Firt comment first child",
        username: "Sparrow",
        userId: "2",
        parentId: "1",
        createdAt: "2022-05-10T18:00:33.010+02:00",
        replyTo: "Jack",
      },
    ],
    views: "107",
    author: "Philip Maxwell",
    publicationDate: "August 4, 2022",
    description:
      "\t\t\tUkraine midfielder Oleksandr Zinchenko broke into tears on the eve of his team’s crucial World Cup qualifier with Scotland and said he wanted above everything to see peace in his homeland. Ukraine, which has been ravaged by war since Russia’s invasion in February, face Scotland at Hampden Park on Wednesday and if they win that game they will go on to take on Wales in Cardiff on Sunday for a place in the finals in Qatar in November. \n\n\t\t\tBut Zinchenko, who plays for Premier League champions Manchester City, said the prospect of World Cup qualification was secondary to the main hope of his countrymen.",
  },
];

export default data;
